# Generated by Django 4.2.6 on 2023-12-01 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_art', models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='album_covers')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('artist', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('format', models.CharField(choices=[('Digital download', 'Digital download'), ('CD', 'CD'), ('Vinyl', 'Vinyl')], max_length=20)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_album_viewer.album')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('album_comments', models.ManyToManyField(related_name='user_comments', to='app_album_viewer.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('running_time', models.IntegerField()),
                ('albums', models.ManyToManyField(related_name='song_albums', to='app_album_viewer.album')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_album_viewer.user'),
        ),
        migrations.AddField(
            model_name='album',
            name='comments',
            field=models.ManyToManyField(related_name='album_comments', to='app_album_viewer.comment'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='album_songs', to='app_album_viewer.song'),
        ),
    ]
