# Generated by Django 4.2.6 on 2023-12-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
