# Generated by Django 4.2.6 on 2023-12-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(blank=True, default='default_cover.png', null=True, upload_to='album_covers'),
        ),
    ]
