# Generated by Django 4.2.6 on 2023-12-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0005_alter_album_cover_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(blank=True, default='album_covers/default_cover.png', null=True, upload_to='album_covers'),
        ),
    ]
