# Generated by Django 4.2.6 on 2023-12-13 21:54

import app_album_viewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0008_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[app_album_viewer.models.validate_positive]),
        ),
    ]
